---

- name: Download cronwrap
  get_url:
    url: '{{ cronwrap_url }}'
    dest: '{{ cronwrap_install_path }}/cronwrap'
    force: True
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: Ensure dependencies are installed
  package:
    name: '{{ item }}'
    state: present
  with_items: '{{ cronwrap_deps }}'
