---

- name: Download cronwrap
  get_url:
    url: '{{ cronwrap_url }}'
    dest: '{{ cronwrap_install_path }}/cronwrap'
  register: get_url

- name: Ensure permissions are correct
  file:
    path: '{{ cronwrap_install_path }}/cronwrap'
    mode: '0755'
    owner: 'root'
    group: 'root'

- name: Ensure dependencies are installed
  package:
    name: '{{ item }}'
    state: present
  with_items: '{{ cronwrap_deps_list }}'
