---

driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
  options:
    config-file: molecule/yamllint.yml
verifier:
  name: testinfra
  lint:
    name: flake8
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default

platforms:
  - name: cronwrap-bionic64
    box: 'ubuntu/bionic64'
  - name: cronwrap-zesty64
    box: 'ubuntu/zesty64'
  - name: cronwrap-xenial64
    box: 'ubuntu/xenial64'
  - name: cronwrap-trusty64
    box: 'ubuntu/trusty64'
  - name: cronwrap-stretch64
    box: 'debian/stretch64'
