---

- hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Ensure python2 is present
      raw: 'which python || apt-get install -y python python-simplejson'
      changed_when: false

- hosts: all
  become: true
  vars:
    cronwrap_user: 'cron@jabber.org'
    cronwrap_password: 'testpassword'
    cronwrap_host: 'jabber.org'
    cronwrap_recipients: 'admin@jabber.org'
  roles:
    - ansible-cronwrap
